package org.example.ws.model;


import javax.persistence.*;


// denotes class to be JPA persistent entity model class
// and registered by spring data framework
@Entity
@Table(name="greetings")
public class Greeting {


    // @Id means PK for entity
    // @GeneratedValue tells JPA values for this are generated by underlying DB

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    private Integer id;

    @Column(name="greet")
    private String greet;

//    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "patient_detail_id_seq")
//    @SequenceGenerator(name = " patient_detail_id_seq ", sequenceName = " patient_detail_id_seq ", allocationSize = 1)


    public Greeting(String greet) {
        this.greet = greet;
    }

    public Greeting() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public void setText(String greet) {
        this.greet = greet;
    }

    public String getGreet() {
        return this.greet;
    }
}
