REM
REM  Create_EFCodd_Version_X_Script_02.sql
REM
REM  Date:     Jan 22, 2011
REM
REM  For:      OCA Oracle SQL Expert Certification Exam Guide (Oracle Press)
REM  
REM  Author:   Steve O'Hearn
REM
REM  Email:    soh@corbinian.com
REM  
REM  Purpose:  This is a second of two scripts.
REM
REM            This script is a collection of various 
REM            SQL statements used to build different
REM            objects referenced throughout the book.
REM
REM            Remember, the goal of the book is not to build a single schema
REM            but rather to analyze all of the complex subjects
REM            that are tested on the certification exam.  
REm            With that understanding, you may find the script below
REM            helpful with your study and preparation to take the exam.
REM
REM            

REM
REM Additional Items
REM

SELECT   SHIP_NAME, CAPACITY, LENGTH
FROM     SHIPS;


DROP   TABLE    BRANCH_OFFICE_ACCOUNTS CASCADE CONSTRAINTS;
DROP   SEQUENCE SEQ_ACCOUNT_ID;

CREATE TABLE BRANCH_OFFICE_ACCOUNTS
(ACCOUNT_ID  NUMBER,
 CRUISE_NAME VARCHAR2(30),
 START_DATE  DATE,
 END_DATE    DATE
 );

CREATE SEQUENCE SEQ_ACCOUNT_ID;

INSERT INTO BRANCH_OFFICE_ACCOUNTS (ACCOUNT_ID, CRUISE_NAME, START_DATE, END_DATE)
VALUES (SEQ_ACCOUNT_ID.NEXTVAL,'Hawaii','11-JUL-11','24-JUL-11');
INSERT INTO BRANCH_OFFICE_ACCOUNTS (ACCOUNT_ID, CRUISE_NAME, START_DATE, END_DATE)
VALUES (SEQ_ACCOUNT_ID.NEXTVAL,'Hawaii','10-OCT-11','23-OCT-11');
INSERT INTO BRANCH_OFFICE_ACCOUNTS (ACCOUNT_ID, CRUISE_NAME, START_DATE, END_DATE)
VALUES (SEQ_ACCOUNT_ID.NEXTVAL,'Mexico','04-OCT-11','17-OCT-11');
INSERT INTO BRANCH_OFFICE_ACCOUNTS (ACCOUNT_ID, CRUISE_NAME, START_DATE, END_DATE)
VALUES (SEQ_ACCOUNT_ID.NEXTVAL,'Mexico','06-DEC-11','19-DEC-11');


REM
REM For examples
REM

DROP   SEQUENCE SEQ_BOOK_CONTENT_ID;
DROP   TABLE    BOOK_CONTENTS CASCADE CONSTRAINTS;

CREATE TABLE BOOK_CONTENTS
(  BOOK_CONTENT_ID   NUMBER
 , CHAPTER_TITLE     VARCHAR2(30)
 , PAGE_NUMBER       NUMBER(4)
);

CREATE SEQUENCE SEQ_BOOK_CONTENT_ID;

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Preface'
   , NULL);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Introduction'
   , 1);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 1'
   , 5);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 2'
   , 23);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 3'
   , 57);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Index'
   , 79);

REM
REM For examples
REM

DROP   TABLE    ORDER_ADDRESSES CASCADE CONSTRAINTS;
DROP   SEQUENCE SEQ_ORDER_ADDRESS_ID;

CREATE TABLE ORDER_ADDRESSES
(  ORDER_ADDRESS_ID NUMBER
 , ADDRESS1         VARCHAR2(40)
 , ADDRESS2         VARCHAR2(40)
);

CREATE SEQUENCE SEQ_ORDER_ADDRESS_ID;
 
INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 ( SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Tulsa, OK 74103');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Bugscuffle, TN 37183');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Issaquah, WA 98027');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Santa Barbara, CA 93109');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Havre De Grace, MD 21078');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Ronks, PA 17572');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Weeki Wachee, FL 34607');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Kalamazoo, MI 49001');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Little Egg Harbor Township, NJ 08087');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Pumpkin Center, OK 74451');

INSERT INTO ORDER_ADDRESSES
 (ORDER_ADDRESS_ID, ADDRESS1, ADDRESS2)
 VALUES
 (SEQ_ORDER_ADDRESS_ID.NEXTVAL, NULL
  , 'Woonsocket, RI 02895');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '01-OCT-10'
   , 'RO-01'
   , '2 pct on 30'
   , 1
   , 1308.23
   , '03-OCT-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '17-JAN-10'
   , 'cre-kit-A1233-V01'
   , NULL
   , 2
   , 2503.75
   , '23-JAN-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '12-FEB-10'
   , 'ae-TRR'
   , NULL
   , 2
   , 9500.23
   , '23-JAN-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '07-APR-10'
   , 'INV-PR-0101'
   , NULL
   , 2
   , 230.23
   , '07-MAY-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '12-MAY-10'
   , 'INV-PR-0189'
   , NULL
   , 2
   , 19423.00
   , '21-MAY-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '16-JUN-10'
   , 'INV-PR-2389'
   , NULL
   , 2
   , 827.23
   , '02-JUL-10');

INSERT INTO INVOICES
  (  INVOICE_ID
   , INVOICE_DATE
   , ACCOUNT_NUMBER
   , TERMS_OF_DISCOUNT
   , VENDOR_ID
   , TOTAL_PRICE
   , SHIPPING_DATE)
  VALUES
  (  SEQ_INVOICE_ID.NEXTVAL
   , '04-AUG-10'
   , 'D-230.23223'
   , NULL
   , 2
   , 33500.23
   , '14-AUG-10');

REM
REM For examples
REM

DROP TABLE SCORES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_SCORE_ID;

CREATE TABLE SCORES(
   SCORE_ID NUMBER
 , TEST_SCORE VARCHAR2(5)
 , UPDATED_TEST_SCORE VARCHAR2(5)
 , CONSTRAINT PK_SCORE_ID PRIMARY KEY (SCORE_ID)
);
CREATE SEQUENCE SEQ_SCORE_ID;
INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,95,95);
INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,55,75);
INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,83,83);


DROP TABLE GRADING CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_GRADING_ID;
CREATE TABLE GRADING(
   GRADING_ID NUMBER
 , GRADE      CHAR(1)
 , SCORE_MIN  NUMBER(3)
 , SCORE_MAX  NUMBER(3)
 , CONSTRAINT PK_GRADING_ID PRIMARY KEY (GRADING_ID)
);
CREATE SEQUENCE SEQ_GRADING_ID;

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'A', 90, 100);
INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'B', 80, 89);
INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'C', 70, 79);
INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'D', 60, 69);
INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'E', 50, 59);


COMMIT;

REM
REM For set operator exercises
REM

DROP   TABLE    STORE_INVENTORY CASCADE CONSTRAINTS;
DROP   SEQUENCE SEQ_NUM;	

CREATE TABLE STORE_INVENTORY
(  NUM         NUMBER
 , AISLE       VARCHAR2(7)
 , PRODUCT     VARCHAR2(15)
 , LAST_ORDER  VARCHAR2(12)
 , CONSTRAINT  PK_NUM PRIMARY KEY (NUM)
);

CREATE SEQUENCE SEQ_NUM;

INSERT INTO STORE_INVENTORY
(  NUM, AISLE, PRODUCT , LAST_ORDER) 
VALUES 
(  77 , 'F02', 'Jacket', '2009-09-09');

INSERT INTO STORE_INVENTORY
(  NUM, AISLE, PRODUCT , LAST_ORDER) 
VALUES 
(  78 , 'B11', 'Towel', '2009-11-11');

INSERT INTO STORE_INVENTORY
(  NUM, AISLE, PRODUCT , LAST_ORDER) 
VALUES 
(  79 , 'SP01', 'Lava lamp', '2009-12-21');

DROP   TABLE    FURNISHINGS CASCADE CONSTRAINTS;
DROP   SEQUENCE SEQ_CAT#;

CREATE TABLE FURNISHINGS
(  CAT#        NUMBER
 , ITEM_NAME   VARCHAR2(15)
 , ADDED       DATE
 , SECTION     VARCHAR2(10)
 , CONSTRAINT  PK_CAT# PRIMARY KEY (CAT#)
);

CREATE SEQUENCE SEQ_CAT#;

INSERT INTO FURNISHINGS
( CAT#, ITEM_NAME, ADDED, SECTION)
VALUES
( 1, 'Side table', '23-DEC-09', 'LR');

INSERT INTO FURNISHINGS
( CAT#, ITEM_NAME, ADDED, SECTION)
VALUES
( 2, 'Desk', '12-SEP-09', 'BR');

INSERT INTO FURNISHINGS
( CAT#, ITEM_NAME, ADDED, SECTION)
VALUES
( 3, 'Towel', '10-OCT-09', 'BA');


COMMIT;

REM
REM For hierarchical query chapter exercises
REM

DROP   TABLE DISTRIBUTORS CASCADE CONSTRAINTS;
CREATE TABLE DISTRIBUTORS
(  ID       NUMBER(3) PRIMARY KEY
 , LOCATION VARCHAR2(20)
 , LOC_TYPE VARCHAR2(10)
 , UPLINE   NUMBER(3)
);

ALTER TABLE DISTRIBUTORS
  ADD CONSTRAINT FK_DI_DI 
  FOREIGN KEY (UPLINE)
  REFERENCES DISTRIBUTORS (ID);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(1,'New York','HQ', NULL);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(2,'Memphis','REGIONAL', 1);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(3,'Minneapolis','REGIONAL', 1);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(4,'Salt Lake','REGIONAL', 1);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(5,'Atlanta','LOCAL', 2);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(6,'Wichita','LOCAL', 2);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(7,'Sacramento','LOCAL', 4);

INSERT INTO DISTRIBUTORS
(ID, LOCATION, LOC_TYPE, UPLINE)
VALUES
(8,'El Paso','LOCAL', 4);

COMMIT;

DROP   TABLE DECKS CASCADE CONSTRAINTS;
CREATE TABLE DECKS
(  DECK_ID    NUMBER(3) PRIMARY KEY
 , SHIP_ID    NUMBER(7)
 , DECK_NAME  VARCHAR2(20));

ALTER TABLE DECKS 
      ADD CONSTRAINT FO_DE_SH FOREIGN KEY (SHIP_ID)
      REFERENCES SHIPS (SHIP_ID);

DROP   SEQUENCE SEQ_DECK_ID;
CREATE SEQUENCE SEQ_DECK_ID;

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'GALLEY 1');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'GALLEY 2');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'GALLEY 3');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'RIVIERA');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'MAIN');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'UPPER');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'EMPRESS');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'ATLANTIC');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'PROMENADE');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'LIDO');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'VERANDAH');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'SPORTS');

INSERT INTO DECKS (DECK_ID, SHIP_ID, DECK_NAME)
  VALUES          (SEQ_DECK_ID.NEXTVAL,1,'SUN');


COMMIT;

DROP   TABLE PROVISIONS CASCADE CONSTRAINTS;
CREATE TABLE PROVISIONS
(  PROVISION_ID NUMBER(5) PRIMARY KEY
 , CATEGORY     VARCHAR2(15)
 , DECK_ID      NUMBER(3)
 , PRODUCT      VARCHAR2(25)
 , QTY          NUMBER(5)
);

DROP   SEQUENCE SEQ_PROVISION_ID;
CREATE SEQUENCE SEQ_PROVISION_ID;

ALTER TABLE PROVISIONS
      ADD CONSTRAINT FO_PR_DE 
      FOREIGN KEY (DECK_ID)
      REFERENCES DECKS (DECK_ID);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'LAUNDRY'
   , 1
   , 'Sheets'
   , 240);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'LAUNDRY'
   , 2
   , 'Sheets'
   , 270);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'LAUNDRY'
   , 3
   , 'Sheets'
   , 320);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'LAUNDRY'
   , 4
   , 'Sheets'
   , 375);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'MEAL'
   , 1
   , 'Meal Packs'
   , 650);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'MEAL'
   , 2
   , 'Meal Packs'
   , 690);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'MEAL'
   , 3
   , 'Meal Packs'
   , 750);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'MEAL'
   , 4
   , 'Meal Packs'
   , 820);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'SUPPLIES'
   , 1
   , 'Cleaning'
   , 180);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'SUPPLIES'
   , 2
   , 'Cleaning'
   , 230);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'SUPPLIES'
   , 3
   , 'Cleaning'
   , 256);

INSERT INTO PROVISIONS
  (PROVISION_ID, CATEGORY, DECK_ID, PRODUCT, QTY)
  VALUES
  (  SEQ_PROVISION_ID.NEXTVAL
   , 'SUPPLIES'
   , 4
   , 'Cleaning'
   , 292);

COMMIT;

REM
REM For INSERT . . . SELECT 
REM

DROP   TABLE WO_INV CASCADE CONSTRAINTS;
CREATE TABLE WO_INV
(INV_NO           NUMBER(11) PRIMARY KEY,
 DATE_ENTERED     DATE,
 DATE_SHIPPED     DATE,
 CUST_ACCT        VARCHAR2(30));

DROP   SEQUENCE SEQ_WO_INV;
CREATE SEQUENCE SEQ_WO_INV;

INSERT INTO WO_INV
  (INV_NO, DATE_ENTERED, DATE_SHIPPED, CUST_ACCT)
  VALUES
  (SEQ_WO_INV.NEXTVAL, '12-DEC-09','14-DEC-09','12-DAF2-Z');

INSERT INTO WO_INV
  (INV_NO, DATE_ENTERED, DATE_SHIPPED, CUST_ACCT)
  VALUES
  (SEQ_WO_INV.NEXTVAL, '27-JAN-10','02-FEB-10','12-DAF3');

INSERT INTO WO_INV
  (INV_NO, DATE_ENTERED, DATE_SHIPPED, CUST_ACCT)
  VALUES
  (SEQ_WO_INV.NEXTVAL, '04-FEB-10','14-FEB-10','12-DB');




COMMIT;

DROP TABLE SHIP_CABIN_GRID;
CREATE TABLE SHIP_CABIN_GRID AS
SELECT UPPER(ROOM_TYPE) ROOM_TYPE, ROUND(OCEAN) OCEAN, ROUND(BALCONY) BALCONY, ROUND(NONE) NO_WINDOW
FROM   (SELECT ROOM_TYPE, WINDOW, SQ_FT FROM SHIP_CABINS) 
PIVOT 
(
  AVG(SQ_FT) FOR WINDOW IN ('Ocean' AS OCEAN, 
                            'Balcony' AS BALCONY, 'None' AS NONE)
 );

COMMIT;

REM
REM For MERGE 
REM

DROP   TABLE WWA_INVOICES;

CREATE TABLE WWA_INVOICES
(INV_ID   NUMBER(7) PRIMARY KEY,
 CUST_PO  VARCHAR2(10),
 INV_DATE DATE,
 NOTES    VARCHAR2(200));

DROP   SEQUENCE SEQ_INV_ID;

CREATE SEQUENCE SEQ_INV_ID START WITH 10 INCREMENT BY 10;


INSERT INTO WWA_INVOICES 
  (INV_ID, CUST_PO, INV_DATE)
  VALUES
  (SEQ_INV_ID.NEXTVAL, 'WWA-200', '17-DEC-09');

INSERT INTO WWA_INVOICES 
  (INV_ID, CUST_PO, INV_DATE)
  VALUES
  (SEQ_INV_ID.NEXTVAL, 'WWA-001', '23-DEC-09');

DROP   TABLE ONTARIO_ORDERS;

CREATE TABLE ONTARIO_ORDERS
(ORDER_NUM   NUMBER(11) PRIMARY KEY,
 PO_NUM      VARCHAR2(20),
 SALES_REP   VARCHAR2(20));

DROP   SEQUENCE SEQ_ORDER_NUM;

CREATE SEQUENCE SEQ_ORDER_NUM START WITH 882;

INSERT INTO ONTARIO_ORDERS
  (ORDER_NUM, PO_NUM, SALES_REP)
  VALUES
  (SEQ_ORDER_NUM.NEXTVAL, 'WWA-001', 'C. Nelson');

INSERT INTO ONTARIO_ORDERS
  (ORDER_NUM, PO_NUM, SALES_REP)
  VALUES
  (SEQ_ORDER_NUM.NEXTVAL, 'WWA-017', 'J. Metelsky');

INSERT INTO ONTARIO_ORDERS
  (ORDER_NUM, PO_NUM, SALES_REP)
  VALUES
  (SEQ_ORDER_NUM.NEXTVAL, 'NBC-201', 'D. Knight');

COMMIT;

DROP   TABLE SHIP_INVENTORY CASCADE CONSTRAINTS;
CREATE TABLE SHIP_INVENTORY
(  NUM          NUMBER
 , AISLE        VARCHAR2(7)
 , PRODUCT      VARCHAR2(15)
 , LAST_ORDER   DATE
 , CONSTRAINT   PK_SHIP_INV_NUM PRIMARY KEY (NUM)
);

DROP   SEQUENCE SEQ_SHIP_NUM;	
CREATE SEQUENCE SEQ_SHIP_NUM;

DROP   TABLE    PORT_INVENTORY CASCADE CONSTRAINTS;
CREATE TABLE PORT_INVENTORY
(  NUM          NUMBER
 , AISLE        VARCHAR2(7)
 , PRODUCT      VARCHAR2(15)
 , LAST_ORDER   DATE
 , CONSTRAINT   PK_PORT_INV_NUM PRIMARY KEY (NUM)
);

DROP   SEQUENCE SEQ_PORT_NUM;	
CREATE SEQUENCE SEQ_PORT_NUM;

COMMIT;

INSERT INTO STORE_INVENTORY
  (NUM, AISLE, PRODUCT, LAST_ORDER)
VALUES 
  (SEQ_NUM.NEXTVAL, '1', 'Lemons', SYSDATE);

INSERT INTO STORE_INVENTORY
  (NUM, AISLE, PRODUCT, LAST_ORDER)
VALUES 
  (SEQ_NUM.NEXTVAL, '2', 'Crackers', SYSDATE-2);

INSERT INTO STORE_INVENTORY
  (NUM, AISLE, PRODUCT, LAST_ORDER)
VALUES 
  (SEQ_NUM.NEXTVAL, '3', 'Soup', SYSDATE-3);

COMMIT;

REM
REM  Chapter on hierarchies
REM

DROP   TABLE EMPLOYEE_CHART;
CREATE TABLE EMPLOYEE_CHART
(  EMPLOYEE_ID  NUMBER(7) PRIMARY KEY, 
   TITLE        VARCHAR2(20), 
   REPORTS_TO   NUMBER(7));

ALTER TABLE EMPLOYEE_CHART
  ADD CONSTRAINT FK_EM_EM 
     FOREIGN KEY (REPORTS_TO)
     REFERENCES EMPLOYEE_CHART (EMPLOYEE_ID);

INSERT INTO EMPLOYEE_CHART VALUES (1, 'CEO', NULL);
INSERT INTO EMPLOYEE_CHART VALUES (2, 'VP',  1);
INSERT INTO EMPLOYEE_CHART VALUES (3, 'SVP', 1);
INSERT INTO EMPLOYEE_CHART VALUES (4, 'CFO', 1);
INSERT INTO EMPLOYEE_CHART VALUES (5, 'Director 1', 2);
INSERT INTO EMPLOYEE_CHART VALUES (6, 'Director 2', 2);
INSERT INTO EMPLOYEE_CHART VALUES (7, 'Director 3', 3);
INSERT INTO EMPLOYEE_CHART VALUES (8, 'Director 4', 3);
INSERT INTO EMPLOYEE_CHART VALUES (9, 'Manager 1',  6);

COMMIT;

REM
REM Chapter 15
REM

DROP   TABLE SALARY_CHART;
CREATE TABLE SALARY_CHART
(ORG_ID      NUMBER(7),
 EMP_TITLE   VARCHAR2(30),
 EMP_INCOME  NUMBER(10,2),
 SUPERIOR    VARCHAR2(30),
 SUP_INCOME  NUMBER(10,2));

DROP   TABLE SHIP_CABIN_STATISTICS;
CREATE TABLE SHIP_CABIN_STATISTICS
(SC_ID       NUMBER(7),
 ROOM_TYPE   VARCHAR2(20),
 WINDOW_TYPE VARCHAR2(10),
 SQ_FT       NUMBER(8));



SPOOL OFF;
