REM
REM  Create_EFCodd_Version_X_Script_01.sql
REM
REM  Date:     Jan 22, 2011
REM
REM  For:      OCA Oracle SQL Expert Certification Exam Guide (Oracle Press)
REM  
REM  Author:   Steve O'Hearn
REM
REM  Email:    soh@corbinian.com
REM  
REM  Purpose:  This is the first of two scripts.
REM
REM            This script is intended to be executed as a whole,
REM            to create a basic version of the schema.
REM            However, the book refers to different versions of this schema 
REM            depending on the topic being analyzed.  Remember,
REM            the goal of the book is not to build a single schema
REM            but rather to analyze all of the complex subjects
REM            that are tested on the certification exam.  
REm            With that understanding, you may find the script below
REM            helpful with your study and preparation to take the exam.
REM
REM
REM            
REM


ALTER SYSTEM SET DEFERRED_SEQGMENT_CREATION = FALSE;

SPOOL CREATE_EFCODD_REPORT.TXT

SET ECHO ON

REM 
REM  Clear out old objects
REM

DROP   TABLE EMPLOYEES      CASCADE CONSTRAINTS;
DROP   TABLE POSITIONS      CASCADE CONSTRAINTS;
DROP   TABLE PORTS          CASCADE CONSTRAINTS;
DROP   TABLE SHIPS          CASCADE CONSTRAINTS;
DROP   TABLE CRUISES        CASCADE CONSTRAINTS;
DROP   TABLE CRUISE_TYPES   CASCADE CONSTRAINTS;
DROP   TABLE WORK_HISTORY   CASCADE CONSTRAINTS;
DROP   TABLE ERRORS         CASCADE CONSTRAINTS;
DROP   TABLE PAY_HISTORY    CASCADE CONSTRAINTS;
DROP   TABLE VENDORS        CASCADE CONSTRAINTS;
DROP   TABLE PROJECTS       CASCADE CONSTRAINTS;
DROP   TABLE SHIP_CABINS    CASCADE CONSTRAINTS;
DROP   TABLE ADDRESSES      CASCADE CONSTRAINTS;
DROP   TABLE ONLINE_SUBSCRIBERS 
                            CASCADE CONSTRAINTS;
DROP   TABLE CRUISE_CUSTOMERS 
                            CASCADE CONSTRAINTS;
DROP   TABLE CRUISE_ORDERS  CASCADE CONSTRAINTS;
DROP   TABLE INVOICES       CASCADE CONSTRAINTS;
DROP   TABLE CONTACT_EMAILS CASCADE CONSTRAINTS;

DROP   SEQUENCE SEQ_EMPLOYEE_ID;
DROP   SEQUENCE SEQ_POSITION_ID;
DROP   SEQUENCE SEQ_SHIP_ID;
DROP   SEQUENCE SEQ_PORT_ID;
DROP   SEQUENCE SEQ_CRUISE_TYPE_ID;
DROP   SEQUENCE SEQ_PAY_HISTORY_ID;
DROP   SEQUENCE SEQ_PROJECT_ID;
DROP   SEQUENCE SEQ_SHIP_CABIN_ID;
DROP   SEQUENCE SEQ_WORK_HISTORY_ID;
DROP   SEQUENCE SEQ_ADDRESS_ID;
DROP   SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID;
DROP   SEQUENCE SEQ_CRUISE_CUSTOMER_ID;
DROP   SEQUENCE SEQ_VENDOR_ID;
DROP   SEQUENCE SEQ_INVOICE_ID;
DROP   SEQUENCE SEQ_CRUISE_ORDER_ID;
DROP   SEQUENCE SEQ_CONTACT_EMAIL_ID;

REM
REM Create tables
REM

CREATE TABLE EMPLOYEES
(  EMPLOYEE_ID         NUMBER(7)
 , SHIP_ID             NUMBER(7)
 , FIRST_NAME          VARCHAR2(20)
 , LAST_NAME           VARCHAR2(30)
 , POSITION_ID         NUMBER
 , SSN                 VARCHAR2(11)
 , DOB                 DATE
 , PRIMARY_PHONE       VARCHAR2(20)
 , CONSTRAINT          PK_EMPLOYEES 
                       PRIMARY KEY (EMPLOYEE_ID)
); 

CREATE TABLE POSITIONS
(  POSITION_ID         NUMBER(4)
 , POSITION            VARCHAR2(20)
 , REPORTS_TO          NUMBER
 , EXEMPT              CHAR(1)
 , MIN_SALARY          NUMBER(10,2)
 , MAX_SALARY          NUMBER(10,2)
 , CONSTRAINT          PK_POSITIONS 
                       PRIMARY KEY (POSITION_ID)
);

CREATE TABLE PORTS
(  PORT_ID             NUMBER
 , PORT_NAME           VARCHAR2(20)
 , COUNTRY             VARCHAR2(40)
 , CAPACITY            NUMBER
 , CONSTRAINT          PK_PORT 
                       PRIMARY KEY (PORT_ID)
);

ALTER TABLE PORTS ADD TOT_SHIPS_ASSIGNED NUMBER(7);
ALTER TABLE PORTS ADD TOT_SHIPS_ASGN_CAP NUMBER(7);

CREATE TABLE SHIPS
(  SHIP_ID             NUMBER(7)
 , SHIP_NAME           VARCHAR2(20)
 , CAPACITY            NUMBER
 , LENGTH              NUMBER
 , HOME_PORT_ID        NUMBER
 , CONSTRAINT          PK_SHIP 
                       PRIMARY KEY (SHIP_ID)
);

CREATE TABLE CRUISES
(  CRUISE_ID           NUMBER
 , CRUISE_TYPE_ID      NUMBER
 , CRUISE_NAME         VARCHAR2(20)
 , SHIP_ID             NUMBER(7)
 , CAPTAIN_ID          NUMBER
 , START_DATE          DATE
 , END_DATE            DATE
 , STATUS              VARCHAR2(5)
 , CONSTRAINT          PK_CRUISE 
                       PRIMARY KEY (CRUISE_ID)
);

CREATE TABLE CRUISE_TYPES
(  CRUISE_TYPE_ID      NUMBER
 , CRUISE_TYPE         VARCHAR(20)
 , CRUISE_LENGTH       NUMBER
 , CONSTRAINT          PK_CRUISE_TYPE_ID 
                       PRIMARY KEY (CRUISE_TYPE_ID)
);

CREATE TABLE WORK_HISTORY
(  WORK_HISTORY_ID    NUMBER
 , EMPLOYEE_ID         NUMBER
 , START_DATE          DATE
 , END_DATE            DATE
 , SHIP_ID             NUMBER(7)
 , STATUS              VARCHAR2(10)
 , CONSTRAINT          PK_WORK_HISTORY 
                       PRIMARY KEY (WORK_HISTORY_ID)
);

CREATE TABLE ERRORS
(  ERROR_ID            NUMBER
 , MESSAGE             VARCHAR2(80)
 , CONSTRAINT          PK_ERROR 
                       PRIMARY KEY (ERROR_ID)
);

CREATE TABLE PAY_HISTORY
(  PAY_HISTORY_ID      NUMBER
 , EMPLOYEE_ID         NUMBER
 , SALARY              NUMBER(10,2)
 , START_DATE          DATE
 , END_DATE            DATE
 , CONSTRAINT          PK_PAY_HISTORY_ID 
                       PRIMARY KEY (PAY_HISTORY_ID)
);

CREATE TABLE VENDORS
(  VENDOR_ID           NUMBER
 , VENDOR_NAME         VARCHAR2(20)
 , STATUS              NUMBER(3)
 , CATEGORY            VARCHAR2(10)
 , CONSTRAINT          PK_VENDOR_ID
                       PRIMARY KEY (VENDOR_ID)
);

CREATE TABLE PROJECTS
(  PROJECT_ID          NUMBER
 , SHIP_ID             NUMBER(7)
 , PURPOSE             VARCHAR2(30)
 , PROJECT_NAME        VARCHAR2(40)
 , PROJECT_COST        NUMBER
 , DAYS                NUMBER
 , CONSTRAINT          PK_PROJECT_ID
                       PRIMARY KEY (PROJECT_ID)
 , CONSTRAINT          CK_PROJECT_COST 
                       CHECK (PROJECT_COST < 1000000)
);

CREATE TABLE SHIP_CABINS
(  SHIP_CABIN_ID       NUMBER
 , SHIP_ID             NUMBER(7)
 , ROOM_NUMBER         VARCHAR2(5)
 , ROOM_STYLE          VARCHAR2(10)
 , ROOM_TYPE           VARCHAR2(20)
 , WINDOW              VARCHAR2(10)
 , GUESTS              NUMBER(3)
 , SQ_FT               NUMBER(6)
 , BALCONY_SQ_FT       NUMBER(6)
 , CONSTRAINT          PK_SHIP_CABIN_ID 
                       PRIMARY KEY (SHIP_CABIN_ID)
 , CONSTRAINT          CK_WINDOW 
                       CHECK (WINDOW IN ('Ocean',
                              'Balcony', 'None'))
);

CREATE TABLE ADDRESSES
(
   ADDRESS_ID          NUMBER
 , EMPLOYEE_ID         NUMBER
 , STREET_ADDRESS      VARCHAR2(40)
 , STREET_ADDRESS2     VARCHAR2(40)
 , CITY                VARCHAR2(30)
 , STATE               VARCHAR2(2)
 , ZIP                 VARCHAR2(5)
 , ZIP_PLUS            VARCHAR2(4)
 , COUNTRY             VARCHAR2(20)
 , CONTACT_EMAIL       VARCHAR2(80)
 , CONSTRAINT          PK_ADDRESS_ID
                       PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE ONLINE_SUBSCRIBERS
(
   ONLINE_SUBSCRIBER_ID NUMBER
 , SUB_DATE             DATE
 , EMAIL                VARCHAR2(120)
 , FIRSTNAME            VARCHAR2(20)
 , LASTNAME             VARCHAR2(30)
 , COMPANY              VARCHAR2(30)
 , CONSTRAINT           PK_ONLINE_SUBSCRIBER_ID
                        PRIMARY KEY (ONLINE_SUBSCRIBER_ID)
);

CREATE TABLE CRUISE_CUSTOMERS
(  CRUISE_CUSTOMER_ID   NUMBER
 , FIRST_NAME           VARCHAR2(20)
 , LAST_NAME            VARCHAR2(30)
 , CONSTRAINT PK_CRUISE_CUSTOMER_ID 
              PRIMARY KEY (CRUISE_CUSTOMER_ID)
);

CREATE TABLE CONTACT_EMAILS
(  CONTACT_EMAIL_ID    NUMBER(4)
 , CRUISE_CUSTOMER_ID  NUMBER
 , EMAIL_ADDRESS       VARCHAR2(95)
 , EMAIL_TYPE          VARCHAR2(10)
 , STATUS              VARCHAR2(7)
 , CONSTRAINT PK_CONTACT_EMAIL_ID 
              PRIMARY KEY (CONTACT_EMAIL_ID)
);

CREATE TABLE CRUISE_ORDERS
(  CRUISE_ORDER_ID      NUMBER
 , ORDER_DATE           DATE
 , POSTING_DATE         DATE
 , CRUISE_CUSTOMER_ID   NUMBER
 , SHIP_ID              NUMBER(7)
 , CONSTRAINT PK_CRUISE_ORDER_ID 
              PRIMARY KEY (CRUISE_ORDER_ID)
);

CREATE TABLE INVOICES
(  INVOICE_ID          NUMBER
 , INVOICE_DATE        DATE
 , ACCOUNT_NUMBER      VARCHAR2(80)
 , TERMS_OF_DISCOUNT   VARCHAR2(20)
 , VENDOR_ID           NUMBER
 , TOTAL_PRICE         NUMBER(8,2)
 , SHIPPING_DATE       DATE
 , CONSTRAINT PK_INVOICE_ID PRIMARY KEY (INVOICE_ID)
);

ALTER TABLE SHIP_CABINS
ADD CONSTRAINT FK_SHIP_ID
  FOREIGN KEY (SHIP_ID)
  REFERENCES SHIPS (SHIP_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_SHIPS
  FOREIGN KEY (SHIP_ID)
  REFERENCES SHIPS (SHIP_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_POSITIONS
  FOREIGN KEY (POSITION_ID)
  REFERENCES POSITIONS (POSITION_ID);

ALTER TABLE WORK_HISTORY
ADD CONSTRAINT FK_WORK_HISTORY_EMPLOYEES
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE SHIPS
ADD CONSTRAINT FK_SHIPS_PORTS
  FOREIGN KEY (HOME_PORT_ID)
  REFERENCES PORTS (PORT_ID);
ALTER TABLE CRUISES
ADD CONSTRAINT FK_CRUISES_CRUISE_TYPES
  FOREIGN KEY (CRUISE_TYPE_ID)
  REFERENCES CRUISE_TYPES (CRUISE_TYPE_ID);

ALTER TABLE CRUISES
ADD CONSTRAINT FK_CRUISES_SHIPS
  FOREIGN KEY (SHIP_ID)
  REFERENCES SHIPS (SHIP_ID);

ALTER TABLE CRUISES
ADD CONSTRAINT FK_CRUISES_EMPLOYEES
  FOREIGN KEY (CAPTAIN_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE PAY_HISTORY
ADD CONSTRAINT FK_PAY_HISTORY_EMPLOYEE
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE ADDRESSES
ADD CONSTRAINT FK_ADDRESSES_EMPLOYEES
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE PROJECTS
ADD CONSTRAINT FK_PROJECTS_SHIPS
  FOREIGN KEY (SHIP_ID)
  REFERENCES SHIPS (SHIP_ID);

ALTER TABLE INVOICES
ADD CONSTRAINT FK_IN_VE
  FOREIGN KEY (VENDOR_ID)
  REFERENCES VENDORS (VENDOR_ID);

ALTER TABLE CRUISE_ORDERS
ADD CONSTRAINT FK_OR_CU
  FOREIGN KEY (CRUISE_CUSTOMER_ID)
  REFERENCES CRUISE_CUSTOMERS (CRUISE_CUSTOMER_ID);

ALTER TABLE CRUISE_ORDERS
ADD CONSTRAINT FK_OR_SH
  FOREIGN KEY (SHIP_ID)
  REFERENCES SHIPS (SHIP_ID);

ALTER TABLE POSITIONS
ADD CONSTRAINT FK_PO_PO
  FOREIGN KEY (REPORTS_TO)
  REFERENCES POSITIONS (POSITION_ID);

ALTER TABLE CONTACT_EMAILS
  ADD CONSTRAINT FK_CE_CC
  FOREIGN KEY (CRUISE_CUSTOMER_ID)
  REFERENCES CRUISE_CUSTOMERS (CRUISE_CUSTOMER_ID);


REM
REM Create indexes
REM

CREATE INDEX IX_EMPLOYEES ON EMPLOYEES (LAST_NAME);

REM
REM Create Sequences
REM

CREATE SEQUENCE SEQ_EMPLOYEE_ID;
CREATE SEQUENCE SEQ_POSITION_ID;
CREATE SEQUENCE SEQ_SHIP_ID;
CREATE SEQUENCE SEQ_PORT_ID;
CREATE SEQUENCE SEQ_CRUISE_TYPE_ID;
CREATE SEQUENCE SEQ_PAY_HISTORY_ID;
CREATE SEQUENCE SEQ_PROJECT_ID;
CREATE SEQUENCE SEQ_SHIP_CABIN_ID;
CREATE SEQUENCE SEQ_WORK_HISTORY_ID;
CREATE SEQUENCE SEQ_ADDRESS_ID;
CREATE SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID;
CREATE SEQUENCE SEQ_VENDOR_ID;
CREATE SEQUENCE SEQ_CRUISE_CUSTOMER_ID;
CREATE SEQUENCE SEQ_INVOICE_ID;
CREATE SEQUENCE SEQ_CRUISE_ORDER_ID;
CREATE SEQUENCE SEQ_CONTACT_EMAIL_ID;

REM
REM Insert data
REM

INSERT INTO CRUISE_TYPES
(  CRUISE_TYPE_ID, CRUISE_TYPE, CRUISE_LENGTH)
VALUES
(  SEQ_CRUISE_TYPE_ID.NEXTVAL
 , 'Eastern Carribean'
 , 3)
;

INSERT INTO CRUISE_TYPES
(  CRUISE_TYPE_ID, CRUISE_TYPE, CRUISE_LENGTH)
VALUES
(  SEQ_CRUISE_TYPE_ID.NEXTVAL
 , 'Eastern Carribean'
 , 5)
;

INSERT INTO CRUISE_TYPES
(  CRUISE_TYPE_ID, CRUISE_TYPE, CRUISE_LENGTH)
VALUES
(  SEQ_CRUISE_TYPE_ID.NEXTVAL
 , 'Western Carribean'
 , 3)
;

INSERT INTO CRUISE_TYPES
(  CRUISE_TYPE_ID, CRUISE_TYPE, CRUISE_LENGTH)
VALUES
(  SEQ_CRUISE_TYPE_ID.NEXTVAL
 , 'Western Carribean'
 , 5)
;

INSERT INTO CRUISE_TYPES
(  CRUISE_TYPE_ID, CRUISE_TYPE, CRUISE_LENGTH)
VALUES
(  SEQ_CRUISE_TYPE_ID.NEXTVAL
 , 'Transatlantic'
 , 3)
;

COMMIT;

REM
REM INSERT INTO POSITIONS
REM

INSERT INTO POSITIONS
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Captain', NULL, 240000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Director', 1, 175000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Manager', 2, 120000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Crew Chief', 2, 88300);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Crew', 4, 65000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES                
  (  SEQ_POSITION_ID.NEXTVAL, 'Restaurant Chief', 3, 78000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES                
  (  SEQ_POSITION_ID.NEXTVAL, 'Chef', 6, 78000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES                
  (  SEQ_POSITION_ID.NEXTVAL, 'Maitre D', 6, 67000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES                
  (  SEQ_POSITION_ID.NEXTVAL, 'Server', 7, 24000);

REM
REM INSERT INTO PORTS
REM

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Baltimore', 'USA', 2)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Charleston', 'USA', 2)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Tampa', 'USA', 8)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Miami', 'USA', 6)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Galveston', 'USA', 4)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'San Diego', 'USA', 4)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'San Francisco', 'USA', 3)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Los Angeles', 'USA', 4)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Honolulu', 'USA', 6)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'St. Thomas', 'USA', 6)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'San Juan', 'USA', 3)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Nassau', 'Bahamas', 7)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Grand Cayman', 'UK', 3)
;

REM
REM INSERT INTO SHIPS
REM

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Crystal', 2052, 855, 1) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Elegance', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Champion', 2974, 952, NULL) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Victorious', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Grandeur', 2446, 916, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Prince', 395, 470, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Harmony', 940, 790, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Voyager', 3114, 1020, 2) 
;

REM
REM INSERT INTO EMPLOYEES AND PAY_HISTORY
REM

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Howard','Hoddlestein'
 , 2, 1);

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 73922
 , '04-JUN-01'
 , '');


INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Joe','Smith'
 , 2, 3); 

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 47000
 , '04-JUN-01'
 , '12-DEC-07');

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 58000
 , '13-JUL-09'
 , '');

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Mike','West'
 , 2, 4);

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 37450
 , '04-JUN-01'
 , '08-APR-05');

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 91379
 , '05-FEB-12'
 , '');


INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Alice','Lindon'
 , 2, 3);

INSERT INTO PAY_HISTORY
(  PAY_HISTORY_ID
 , EMPLOYEE_ID
 , SALARY
 , START_DATE
 , END_DATE)
VALUES 
(  SEQ_PAY_HISTORY_ID.NEXTVAL
 , SEQ_EMPLOYEE_ID.CURRVAL
 , 45500
 , '04-JUN-01'
 , '');

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Al','Smith'
 , 2, 1);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Trish','West'
 , 2, 2);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Buffy','Worthington'
 , 2, 1);

REM
REM INSERT INTO PROJECTS
REM

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES                 
  (  SEQ_PROJECT_ID.NEXTVAL
                , 2      , 'Maintenance', 'Deck Resurfacing'       , 964000      , 10);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 3      ,'Maintenance' , 'Lifeboat Inspection'    , 12000       , 3);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Maintenance' , 'Clean Pools'            , 37000       , 5);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Upgrade'     , 'Replace lobby carpeting', 137000      , 5);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Maintenance' , 'Major Engine Service'   , 837000      , 15);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Upgrade'     , 'Remodel Dining Room A'  , 950000      , 45);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Upgrade'     , 'Remodel Dining Room B'  , 925000      , 37);

INSERT INTO PROJECTS 
  (  PROJECT_ID , SHIP_ID, PURPOSE      , PROJECT_NAME             , PROJECT_COST, DAYS)
VALUES               
  (  SEQ_PROJECT_ID.NEXTVAL
                , 1      ,'Maintenance' , 'Lifeboat Inspection'    , 12000       , 3);

REM
REM INSERT INTO SHIP_CABINS
REM

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 102        , 'Suite'    , 'Standard', 'Balcony',      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 103        , 'Stateroom', 'Standard', 'Ocean',      2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 104        , 'Suite'    , 'Standard', 'Balcony' ,      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 105        , 'Stateroom', 'Standard', 'Ocean',      3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 106        , 'Suite'    , 'Standard', 'Balcony' ,      6,   586, 193);
  
INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 107        , 'Suite'    , 'Royal'   , 'Balcony',      5,  1524, 843);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 108        , 'Stateroom', 'Large'   , 'None' ,      2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 109        , 'Stateroom', 'Standard', 'Ocean' ,      2,   180, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 110        , 'Stateroom', 'Large'   , 'Ocean' ,      2,   225, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 701        , 'Suite'    , 'Presidential','Balcony',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 702        , 'Suite'    , 'Presidential','Balcony',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 703        , 'Suite'    , 'Royal'   , 'Balcony' ,      5,  1745, 974);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 704        , 'Suite'    , 'Skyloft' , 'Balcony' ,      8,   722, 410);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 705        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 706        , 'Suite' , 'Standard' , 'Balcony' ,     4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 707        , 'Stateroom' , 'Standard' , 'Ocean' ,     3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 708        , 'Suite' , 'Standard' , 'Balcony' ,     6,   586, 193);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 709        , 'Stateroom' , 'Large' , 'None' ,     2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 710        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   180, NULL);


INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 801        , 'Suite'    , 'Presidential','None',    5,  1142, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 802        , 'Suite'    , 'Presidential','Ocean',    5,  1142, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 803        , 'Suite'    , 'Royal'   , 'Ocean' ,      5,  1745, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 804        , 'Suite'    , 'Skyloft' , 'Ocean' ,      8,   722, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 805        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 806        , 'Suite' , 'Standard' , 'Ocean' ,     4,   533, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 807        , 'Stateroom' , 'Standard' , 'Ocean' ,     3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 808        , 'Suite' , 'Standard' , 'None' ,     6,   586, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 809        , 'Stateroom' , 'Large' , 'None' ,     2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 810        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   180, NULL);

REM
REM INSERT INTO WORK_HISTORY
REM

INSERT INTO WORK_HISTORY 
  (  WORK_HISTORY_ID, EMPLOYEE_ID
   , START_DATE, END_DATE, SHIP_ID, STATUS)
  VALUES 
  (  10, 3, '23-JUN-01', '09-FEB-08', 1, 'Pending');

INSERT INTO WORK_HISTORY 
  (  WORK_HISTORY_ID, EMPLOYEE_ID
   , START_DATE, END_DATE, SHIP_ID, STATUS)
  VALUES 
  (  11, 4, '23-JUN-01', '05-DEC-06', 4, 'Active');

INSERT INTO WORK_HISTORY 
  (  WORK_HISTORY_ID, EMPLOYEE_ID
   , START_DATE, END_DATE, SHIP_ID, STATUS)
  VALUES 
  (  12, 7, '23-JUN-01', '28-SEP-02',  3, 'Pending');

REM
REM INSERT INTO ADDRESSES
REM

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 1
   , '350 Oracle Parkway'
   , NULL
   , 'Redwood City'
   , 'CA'
   , '94065'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '1600 Amphitheatre Parkway'
   , NULL
   , 'Mountain View'
   , 'CA'
   , '94043'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 3
   , '1 Dell Way'
   , NULL
   , 'Round Rock'
   , 'TX'
   , '78682'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 4
   , '29 E Ohio St'
   , NULL
   , 'Chicago'
   , 'IL'
   , '60611'
   , '2707'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 5
   , '5788 Roswell Rd NE'
   , NULL
   , 'Atlanta'
   , 'GA'
   , '30328'
   , '4904'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '10103 100 St NW'
   , NULL
   , 'Edmonton'
   , 'AB'
   , 'T5J'
   , '0N8'
   , 'Canada'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 6
   , '1221 Avenue of the Americas'
   , NULL
   , 'New York'
   , 'NY'
   , '10020'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '239 Baker Street'
   , NULL
   , 'London'
   , NULL
   , 'NW1'
   , '6X3'
   , 'UK'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '1 rue des Carrieres'
   , NULL
   , 'Quebec City'
   , 'QC'
   , 'G1R'
   , '4P5'
   , 'Canada'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 4
   , '2041 S Harbor Blvd'
   , NULL
   , 'Anaheim'
   , 'CA'
   , '92802'
   , '3513'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '600 N Michigan Ave'
   , NULL
   , 'Chicago'
   , 'IL'
   , '60611'
   , '3113'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 6
   , '1515 Sheridan Rd'
   , NULL
   , 'Wilmette'
   , 'IL'
   , '60091'
   , NULL
   , 'USA'
   , NULL
   );

REM
REM INSERT INTO ONLINE_SUBSCRIBERS
REM

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '12-DEC-08'
 , 'pendicott77@kasteelinc.com'
 , 'EDGAR'
 , 'KLINE'
 , 'KLINE AND ASSOCIATES'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '09-APR-09'
 , 'watcher@foursigma.org'
 , 'bill'
 , 'bryant'
 , 'Gold International'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '09-APR-09'
 , 'hardingpal@ckofca.com'
 , 'Ned'
 , 'McLean'
 , 'Harding Company'
); 

REM
REM INSERT INTO VENDORS
REM

INSERT INTO VENDORS 
  (VENDOR_ID, VENDOR_NAME, STATUS, CATEGORY)
  VALUES
  (SEQ_VENDOR_ID.NEXTVAL, 'Acme Steaks', 17, 'Partner');

INSERT INTO VENDORS 
  (VENDOR_ID, VENDOR_NAME, STATUS, CATEGORY)
  VALUES
  (SEQ_VENDOR_ID.NEXTVAL, 'Acme Poker Chips', NULL, 'Supplier');


REM
REM INSERT INTO CRUISE_CUSTOMERS AND CONTACT_EMAILS
REM

INSERT INTO CRUISE_CUSTOMERS
(  CRUISE_CUSTOMER_ID
 , FIRST_NAME
 , LAST_NAME
) VALUES (
   SEQ_CRUISE_CUSTOMER_ID.NEXTVAL
 , 'Nada'
 , 'Gilbert'
);

INSERT INTO CONTACT_EMAILS
(  CONTACT_EMAIL_ID
 , CRUISE_CUSTOMER_ID
 , EMAIL_ADDRESS
 , EMAIL_TYPE
 , STATUS
) VALUES (
   SEQ_CONTACT_EMAIL_ID.NEXTVAL
 , SEQ_CRUISE_CUSTOMER_ID.CURRVAL
 , 'bubblegum@tlivecar.com'
 , 'Work'
 , 'Opt Out'
);

INSERT INTO CRUISE_CUSTOMERS
(  CRUISE_CUSTOMER_ID
 , FIRST_NAME
 , LAST_NAME
) VALUES (
   SEQ_CRUISE_CUSTOMER_ID.NEXTVAL
 , 'Nora'
 , 'MacCaulay'
);

INSERT INTO CONTACT_EMAILS
(  CONTACT_EMAIL_ID
 , CRUISE_CUSTOMER_ID
 , EMAIL_ADDRESS
 , EMAIL_TYPE
 , STATUS
) VALUES (
   SEQ_CONTACT_EMAIL_ID.NEXTVAL
 , SEQ_CRUISE_CUSTOMER_ID.CURRVAL
 , 'nora@astann.com'
 , 'Home'
 , 'Valid'
);

INSERT INTO CRUISE_CUSTOMERS
(  CRUISE_CUSTOMER_ID
 , FIRST_NAME
 , LAST_NAME
) VALUES (
   SEQ_CRUISE_CUSTOMER_ID.NEXTVAL
 , 'William'
 , 'Bryant'
);

INSERT INTO CONTACT_EMAILS
(  CONTACT_EMAIL_ID
 , CRUISE_CUSTOMER_ID
 , EMAIL_ADDRESS
 , EMAIL_TYPE
 , STATUS
) VALUES (
   SEQ_CONTACT_EMAIL_ID.NEXTVAL
 , SEQ_CRUISE_CUSTOMER_ID.CURRVAL
 , 'watcher@foursigma.org'
 , 'Work'
 , 'Valid'
);

SET ECHO OFF

SPOOL OFF;
