/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package me.jeffli.avrosamples.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LogEntry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogEntry\",\"namespace\":\"me.jeffli.avrosamples.model\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"resource\",\"type\":[\"string\",\"null\"]},{\"name\":\"ip\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence resource;
  @Deprecated public java.lang.CharSequence ip;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public LogEntry() {}

  /**
   * All-args constructor.
   */
  public LogEntry(java.lang.CharSequence name, java.lang.CharSequence resource, java.lang.CharSequence ip) {
    this.name = name;
    this.resource = resource;
    this.ip = ip;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return resource;
    case 2: return ip;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: resource = (java.lang.CharSequence)value$; break;
    case 2: ip = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'resource' field.
   */
  public java.lang.CharSequence getResource() {
    return resource;
  }

  /**
   * Sets the value of the 'resource' field.
   * @param value the value to set.
   */
  public void setResource(java.lang.CharSequence value) {
    this.resource = value;
  }

  /**
   * Gets the value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /** Creates a new LogEntry RecordBuilder */
  public static me.jeffli.avrosamples.model.LogEntry.Builder newBuilder() {
    return new me.jeffli.avrosamples.model.LogEntry.Builder();
  }
  
  /** Creates a new LogEntry RecordBuilder by copying an existing Builder */
  public static me.jeffli.avrosamples.model.LogEntry.Builder newBuilder(me.jeffli.avrosamples.model.LogEntry.Builder other) {
    return new me.jeffli.avrosamples.model.LogEntry.Builder(other);
  }
  
  /** Creates a new LogEntry RecordBuilder by copying an existing LogEntry instance */
  public static me.jeffli.avrosamples.model.LogEntry.Builder newBuilder(me.jeffli.avrosamples.model.LogEntry other) {
    return new me.jeffli.avrosamples.model.LogEntry.Builder(other);
  }
  
  /**
   * RecordBuilder for LogEntry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogEntry>
    implements org.apache.avro.data.RecordBuilder<LogEntry> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence resource;
    private java.lang.CharSequence ip;

    /** Creates a new Builder */
    private Builder() {
      super(me.jeffli.avrosamples.model.LogEntry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(me.jeffli.avrosamples.model.LogEntry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.resource)) {
        this.resource = data().deepCopy(fields()[1].schema(), other.resource);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ip)) {
        this.ip = data().deepCopy(fields()[2].schema(), other.ip);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing LogEntry instance */
    private Builder(me.jeffli.avrosamples.model.LogEntry other) {
            super(me.jeffli.avrosamples.model.LogEntry.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.resource)) {
        this.resource = data().deepCopy(fields()[1].schema(), other.resource);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ip)) {
        this.ip = data().deepCopy(fields()[2].schema(), other.ip);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'resource' field */
    public java.lang.CharSequence getResource() {
      return resource;
    }
    
    /** Sets the value of the 'resource' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder setResource(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.resource = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'resource' field has been set */
    public boolean hasResource() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'resource' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder clearResource() {
      resource = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ip' field */
    public java.lang.CharSequence getIp() {
      return ip;
    }
    
    /** Sets the value of the 'ip' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ip = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ip' field has been set */
    public boolean hasIp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ip' field */
    public me.jeffli.avrosamples.model.LogEntry.Builder clearIp() {
      ip = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public LogEntry build() {
      try {
        LogEntry record = new LogEntry();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.resource = fieldSetFlags()[1] ? this.resource : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ip = fieldSetFlags()[2] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
